fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: pl
            editor: ckeditor
            theme: smoothness
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images
                        show_hidden: false
                        upload_allow: ['all']
                        upload_max_size: 5M
